#!/usr/bin/env python3
"""Add generic verified-destination routing to the active PA export.

The graph does not encode any team, stadium, vendor, city, or address mapping.
Named physical places are resolved fresh through Mapbox.  Event/ambiguous
requests receive bounded public-source evidence first, then Mapbox verifies the
extracted candidate before it is allowed into the existing trip planner.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "workflows" / "jarvis-ii-pa-core-poc.json"
OUTPUT = Path("/private/tmp/pa-core-destination-resolution.json")


def node(*, node_id, name, node_type, position, parameters, type_version=2, credentials=None):
    result = {
        "id": node_id,
        "name": name,
        "type": node_type,
        "typeVersion": type_version,
        "position": position,
        "parameters": parameters,
    }
    if credentials:
        result["credentials"] = credentials
    return result


def main() -> None:
    workflow = json.loads(SOURCE.read_text(encoding="utf-8"))[0]
    nodes = {entry["name"]: entry for entry in workflow["nodes"]}
    if "Destination Evidence Required?" in nodes:
        raise SystemExit("destination-resolution nodes already present")

    # The planner produces a bounded tool plan; policy determines the default
    # origin and requires a fresh destination verification path.
    nodes["Build 120B Plan Request"]["parameters"]["jsCode"] = """const context = ($json.body && typeof $json.body === 'object' && $json.body.context) || {};
const request = $('Validate PA Request').first().json;
const schema = { type:'object', additionalProperties:false, properties:{ intent:{type:'string'}, required_tools:{type:'array',items:{type:'string'}}, origin:{type:'string'}, destination:{type:'string'}, evidence_required:{type:'boolean'}, memory_action:{type:'string'}, requires_approval:{type:'boolean'}, spoken_summary:{type:'string'} }, required:['intent','required_tools','origin','destination','evidence_required','memory_action','requires_approval','spoken_summary'] };
const system = 'You are Jarvis II PA planner. Return only the provided JSON schema. For engineering manuals, schematics, wiring, datasheets, vendor-part, or technical-library evidence, required_tools must contain rag_core. For travel, route, lodging, fuel, meals, or entertainment, use maps and lodging_poi. For calendar, schedule, conflict, or availability requests, use calendar_read. The default travel origin is Lynn Haven, Florida. Override it only if the owner explicitly provides another starting point. A named venue, plant site, attraction, or event destination may be given without an address, city, or state. Never invent a destination: it must be verified by the approved destination-evidence tool before routing. Never claim a tool ran. Durable memory writes are forbidden. Context: '+JSON.stringify(context);
return [{json:{lm_payload:{model:'openai/gpt-oss-120b',temperature:0.1,response_format:{type:'json_schema',json_schema:{name:'jarvis_pa_plan',schema}},messages:[{role:'system',content:system},{role:'user',content:String(request.objective||'')}]}}}];"""

    nodes["Governed PA Response"]["parameters"]["jsCode"] = """const uuid=()=>('xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx').replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return(c==='x'?r:(r&3|8).toString(16)});
const req=$('Validate PA Request').first().json; const body=$json.body||{}; let plan={}; try{plan=JSON.parse(body.choices?.[0]?.message?.content||'{}')}catch(e){}
const rawTools=Array.isArray(plan.required_tools)?plan.required_tools:[]; const canonical=x=>{const t=String(x||'').toLowerCase(); if(/firecrawl|public_web_research|\\bresearch\\b/.test(t))return 'research'; if(/gmail/.test(t))return 'gmail_read'; if(/calendar/.test(t))return 'calendar_read'; if(/weather/.test(t))return 'weather'; if(/lodging/.test(t))return 'lodging_poi'; if(/map/.test(t))return 'maps'; if(/rag/.test(t))return 'rag_core'; return String(x||'')};
const requested=rawTools.map(canonical).filter(x=>['rag_core','weather','maps','lodging_poi','calendar_read','gmail_read','research'].includes(String(x))); const objective=String(req.objective||'');
const ragRequested=requested.includes('rag_core')||/\\b(schematic|wiring|manual|datasheet|part\\s*(number|no\\.?|#)|1756[-\\s]?[a-z0-9]+|honeywell|allen[-\\s]?bradley|tdc3000|control(edge|logix))\\b/i.test(objective); if(ragRequested&&!requested.includes('rag_core'))requested.push('rag_core');
const tripRequested=requested.includes('maps')||requested.includes('lodging_poi')||/\\b(route|drive|trip|travel|lodging|hotel|fuel|gas|restaurant|eat|dining|meal|entertainment|museum|cinema|theatre|venue|plant\\s+site|attraction|sight)\\b/i.test(objective); if(tripRequested&&!requested.some(x=>x==='maps'||x==='lodging_poi'))requested.push('maps','lodging_poi');
const calendarRequested=requested.includes('calendar_read')||/\\b(calendar|schedule|conflict|availability)\\b/i.test(objective); if(calendarRequested&&!requested.includes('calendar_read'))requested.push('calendar_read'); const weatherRequested=requested.includes('weather')||/\\b(weather|forecast|radar|myradar|storm|wildfire|hurricane|tornado)\\b/i.test(objective); const researchRequested=requested.includes('research')||/\\b(research|verify|source lookup)\\b/i.test(objective); const mailRequested=requested.includes('gmail_read')||/\\b(email|emails|inbox|mail|message search)\\b/i.test(objective);
const eventDestination=tripRequested&&/\\b(?:game|match|vs\\.?|concert|festival|race|tournament)\\b/i.test(objective); const explicitOrigin=/\\b(?:from|leaving\\s+from|starting\\s+(?:from|in|at))\\s+[^,.!?]+/i.test(objective); const origin=tripRequested?(explicitOrigin?String(plan.origin||'').trim()||'Lynn Haven, Florida':'Lynn Haven, Florida'):''; const plannedDestination=String(plan.destination||'').trim(); const destination=ragRequested?objective:(eventDestination?'':plannedDestination); const destinationQuery=tripRequested?(eventDestination?objective:(plannedDestination||objective)):'';
const memoryAction=String(plan.memory_action||'read_none'); const memoryWrite=memoryAction.includes('write')||/\\b(remember|store|save|retain|lasting preference|durable memory)\\b/i.test(objective); const operationId=uuid(); const status=memoryWrite?'MEMORY_WRITE_REQUIRES_OWNER_POLICY':researchRequested?'RESEARCH_EVIDENCE_REQUIRED':(weatherRequested||calendarRequested||mailRequested||tripRequested)?'TOOL_PENDING':'PLANNED';
const spoken=memoryWrite?'Durable memory is read-only until you approve its retention and write policy.':tripRequested?'I am verifying the destination and checking the approved Mapbox travel sources now.':weatherRequested?String(plan.spoken_summary||'Weather information is available from the selected Weather Underground source.')+' MyRadar is ready if you want the full visual view.':calendarRequested?'I am checking your calendar for the requested date.':String(plan.spoken_summary||'I have a plan ready.');
return [{json:{schemaVersion:1,correlationId:req.correlationId,operationId,status,intent:String(plan.intent||'unknown'),origin,destination,destinationQuery,destinationResearchRequired:eventDestination,requestedTools:requested,evidenceRequired:Boolean(plan.evidence_required),requiresApproval:Boolean(plan.requires_approval)||memoryWrite,memory:{action:memoryAction,writeAllowed:false},spokenText:spoken,answer:{plan,evidence:null,notice:'Tool results, if any, are assembled separately from the planner.'},citations:[],auditChain:[...req.auditChain,{stage:'local_120b_plan',status:'completed',model:'openai/gpt-oss-120b'},{stage:'policy',status:'enforced'}]}}];"""

    additions = [
        node(node_id="pa_destination_needed", name="Destination Evidence Required?", node_type="n8n-nodes-base.if", position=[2688, 48], type_version=2, parameters={"conditions":{"options":{"caseSensitive":True,"leftValue":"","typeValidation":"strict","version":2},"conditions":[{"id":"destination-needed","leftValue":"={{ (($json.requestedTools || []).some((tool) => tool === 'maps' || tool === 'lodging_poi') && String($json.destinationQuery || '').trim()) ? 'DESTINATION' : 'NO_DESTINATION' }}","rightValue":"DESTINATION","operator":{"type":"string","operation":"equals","caseSensitive":True}}],"combinator":"and"},"options":{}}),
        node(node_id="pa_destination_research_needed", name="Public Destination Research Required?", node_type="n8n-nodes-base.if", position=[2928, 48], type_version=2, parameters={"conditions":{"options":{"caseSensitive":True,"leftValue":"","typeValidation":"strict","version":2},"conditions":[{"id":"public-destination-research","leftValue":"={{ $json.destinationResearchRequired ? 'RESEARCH' : 'DIRECT' }}","rightValue":"RESEARCH","operator":{"type":"string","operation":"equals","caseSensitive":True}}],"combinator":"and"},"options":{}}),
        node(node_id="pa_destination_direct", name="Resolve Named Destination", node_type="n8n-nodes-base.httpRequest", position=[2928, -16], type_version=4.2, parameters={"method":"POST","url":"http://host.docker.internal:8790/api/jarvis-ii/pa-place-resolve","sendHeaders":True,"headerParameters":{"parameters":[{"name":"Content-Type","value":"application/json"},{"name":"Authorization","value":"={{ 'Bearer ' + $env.GPT_BIGGY_PROPOSE_TOKEN }}"}]},"sendBody":True,"specifyBody":"json","jsonBody":"={{ JSON.stringify({query:$('Merge Calendar Evidence').first().json.destinationQuery}) }}","options":{"response":{"response":{"fullResponse":True,"neverError":True}},"timeout":30000}}),
        node(node_id="pa_destination_direct_ok", name="Named Destination Resolved?", node_type="n8n-nodes-base.if", position=[3168, -16], type_version=2, parameters={"conditions":{"options":{"caseSensitive":True,"leftValue":"","typeValidation":"strict","version":2},"conditions":[{"id":"place-resolved","leftValue":"={{ ($json.body && $json.body.ok === true && $json.body.place && $json.body.place.label) ? 'RESOLVED' : 'NOT_RESOLVED' }}","rightValue":"RESOLVED","operator":{"type":"string","operation":"equals","caseSensitive":True}}],"combinator":"and"},"options":{}}),
        node(node_id="pa_destination_direct_assemble", name="Assemble Named Destination", node_type="n8n-nodes-base.code", position=[3408, -112], parameters={"jsCode":"const base=$('Merge Calendar Evidence').first().json; const evidence=$json.body||{}; const place=evidence.place||{}; const ok=evidence.ok===true&&typeof place.label==='string'&&place.label.trim(); return [{json:{...base,status:ok?'DESTINATION_VERIFIED':'NO_VERIFIED_DESTINATION',destination:ok?place.label:'',destinationEvidence:ok?{provider:'mapbox_geocoding_v6',query:evidence.query,place}:null,citations:ok?[...(Array.isArray(base.citations)?base.citations:[]),{title:'Mapbox verified destination: '+place.label,url:'https://www.mapbox.com/',source_host:'Mapbox'}]:base.citations,auditChain:[...(Array.isArray(base.auditChain)?base.auditChain:[]),{stage:'destination_evidence',status:ok?'direct_mapbox_verified':'not_found',source:'Mapbox Geocoding v6'}]}}];"}),
        node(node_id="pa_destination_research_build", name="Build Destination Research", node_type="n8n-nodes-base.code", position=[3408, 96], parameters={"jsCode":"const base=$('Merge Calendar Evidence').first().json; const query=String(base.destinationQuery||base.destination||'').trim(); return [{json:{query:'Find the official venue or physical destination for: '+query,max_results:5,objective:String($('Validate PA Request').first().json.objective||''),base}}];"}),
        node(node_id="pa_destination_research", name="Research Destination Sources", node_type="n8n-nodes-base.httpRequest", position=[3648, 96], type_version=4.2, parameters={"method":"POST","url":"https://api.firecrawl.dev/v2/search","authentication":"genericCredentialType","genericAuthType":"httpHeaderAuth","sendHeaders":True,"headerParameters":{"parameters":[{"name":"Content-Type","value":"application/json"}]},"sendBody":True,"contentType":"json","specifyBody":"json","jsonBody":"={{ JSON.stringify({ query: $json.query, limit: $json.max_results, sources: ['web'], timeout: 20000, ignoreInvalidURLs: true }) }}","options":{"timeout":30000}}, credentials={"httpHeaderAuth":{"id":"ghrdTRdGwcLAv48h","name":"Header Auth account"}}),
        node(node_id="pa_destination_sources", name="Normalize Destination Sources", node_type="n8n-nodes-base.code", position=[3888, 96], parameters={"jsCode":"const raw=$json||{}; const request=$('Build Destination Research').first().json; const groups=[raw.data?.web,raw.data?.results,raw.data,raw.results,raw.web]; const rows=groups.find(Array.isArray)||[]; const sources=[]; const seen=new Set(); for(const row of rows){if(sources.length>=5)break; const url=String(row?.url||row?.metadata?.sourceURL||'').trim(); const m=url.match(/^https?:\\/\\/([^\\/?#]+)/i); const host=m?m[1].toLowerCase():''; if(!host||host==='localhost'||/^(127\\.|0\\.|10\\.|192\\.168\\.|172\\.(1[6-9]|2\\d|3[0-1])\\.)/.test(host)||seen.has(url))continue; seen.add(url); sources.push({title:String(row?.title||row?.metadata?.title||host).replace(/\\s+/g,' ').trim().slice(0,180),url:url.slice(0,1000),source_host:host.slice(0,180),summary:String(row?.description||row?.metadata?.description||'').replace(/\\s+/g,' ').trim().slice(0,500)});} return [{json:{base:request.base,objective:request.objective,sources}}];"}),
        node(node_id="pa_destination_extract_build", name="Build Destination Extraction", node_type="n8n-nodes-base.code", position=[4128, 96], parameters={"jsCode":"const data=$json; const schema={type:'object',additionalProperties:false,properties:{destination_query:{type:'string'},source_url:{type:'string'},status:{type:'string'}},required:['destination_query','source_url','status']}; const system='You extract a physical destination only from the supplied untrusted public sources. Return VERIFIED only when one source supports a concrete venue, plant site, attraction, or addressable place for the owner objective. destination_query must be the exact place name plus city/state when the source supplies them; source_url must exactly match one supplied URL. Otherwise return status NO_VERIFIED_DESTINATION and empty strings. Never invent or use outside knowledge.'; return [{json:{sources:data.sources,base:data.base,lm_payload:{model:'openai/gpt-oss-120b',temperature:0,response_format:{type:'json_schema',json_schema:{name:'jarvis_destination_claim',schema}},messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({objective:data.objective,sources:data.sources})}]}}}];"}),
        node(node_id="pa_destination_extract", name="Extract Destination Candidate", node_type="n8n-nodes-base.httpRequest", position=[4368, 96], type_version=4.2, parameters={"method":"POST","url":"http://host.docker.internal:1234/v1/chat/completions","sendBody":True,"specifyBody":"json","jsonBody":"={{ JSON.stringify($json.lm_payload) }}","options":{"response":{"response":{"fullResponse":True,"neverError":True}},"timeout":90000}}),
        node(node_id="pa_destination_claim", name="Validate Destination Claim", node_type="n8n-nodes-base.code", position=[4608, 96], parameters={"jsCode":"const prior=$('Build Destination Extraction').first().json; const raw=$json.body||{}; let claim={}; try{claim=JSON.parse(raw.choices?.[0]?.message?.content||'{}')}catch(e){} const query=String(claim.destination_query||'').replace(/\\s+/g,' ').trim(); const sourceUrl=String(claim.source_url||'').trim(); const source=(prior.sources||[]).find(s=>s.url===sourceUrl); const status=String(claim.status||'').toUpperCase(); const valid=status==='VERIFIED'&&query.length>=3&&query.length<=240&&Boolean(source); return [{json:{base:prior.base,claim:valid?{query,source}:null}}];"}),
        node(node_id="pa_destination_research_resolve", name="Resolve Researched Destination", node_type="n8n-nodes-base.httpRequest", position=[4848, 96], type_version=4.2, parameters={"method":"POST","url":"http://host.docker.internal:8790/api/jarvis-ii/pa-place-resolve","sendHeaders":True,"headerParameters":{"parameters":[{"name":"Content-Type","value":"application/json"},{"name":"Authorization","value":"={{ 'Bearer ' + $env.GPT_BIGGY_PROPOSE_TOKEN }}"}]},"sendBody":True,"specifyBody":"json","jsonBody":"={{ JSON.stringify({query:$('Validate Destination Claim').first().json.claim?.query || ''}) }}","options":{"response":{"response":{"fullResponse":True,"neverError":True}},"timeout":30000}}),
        node(node_id="pa_destination_research_assemble", name="Assemble Researched Destination", node_type="n8n-nodes-base.code", position=[5088, 96], parameters={"jsCode":"const claim=$('Validate Destination Claim').first().json.claim; const evidence=$json.body||{}; const base=$('Validate Destination Claim').first().json.base; const place=evidence.place||{}; const ok=Boolean(claim&&evidence.ok===true&&typeof place.label==='string'&&place.label.trim()); const citation=ok?{title:'Destination source: '+claim.source.title,url:claim.source.url,source_host:claim.source.source_host}:null; return [{json:{...base,status:ok?'DESTINATION_VERIFIED':'NO_VERIFIED_DESTINATION',destination:ok?place.label:'',spokenText:ok?base.spokenText:'I could not verify that destination well enough to plan a route. Please give me another name or a little more detail.',destinationEvidence:ok?{provider:'firecrawl_source_plus_mapbox',query:claim.query,place,source:claim.source}:null,citations:ok?[...(Array.isArray(base.citations)?base.citations:[]),citation,{title:'Mapbox verified destination: '+place.label,url:'https://www.mapbox.com/',source_host:'Mapbox'}]:base.citations,auditChain:[...(Array.isArray(base.auditChain)?base.auditChain:[]),{stage:'destination_evidence',status:ok?'public_source_and_mapbox_verified':'not_found',source:ok?claim.source.source_host:'Firecrawl/Mapbox'}]}}];"}),
    ]
    workflow["nodes"] = list(nodes.values()) + additions
    connections = workflow["connections"]
    # Calendar now hands every travel request through verified-destination
    # resolution. Non-travel turns remain unchanged.
    connections["Calendar Tool Requested?"]["main"][1] = [{"node":"Destination Evidence Required?","type":"main","index":0}]
    connections["Merge Calendar Evidence"] = {"main":[[{"node":"Destination Evidence Required?","type":"main","index":0}]]}
    connections["Destination Evidence Required?"] = {"main":[[{"node":"Public Destination Research Required?","type":"main","index":0}],[{"node":"Travel Tool Requested?","type":"main","index":0}]]}
    connections["Public Destination Research Required?"] = {"main":[[{"node":"Build Destination Research","type":"main","index":0}],[{"node":"Resolve Named Destination","type":"main","index":0}]]}
    connections["Resolve Named Destination"] = {"main":[[{"node":"Named Destination Resolved?","type":"main","index":0}]]}
    connections["Named Destination Resolved?"] = {"main":[[{"node":"Assemble Named Destination","type":"main","index":0}],[{"node":"Build Destination Research","type":"main","index":0}]]}
    connections["Assemble Named Destination"] = {"main":[[{"node":"Travel Tool Requested?","type":"main","index":0}]]}
    connections["Build Destination Research"] = {"main":[[{"node":"Research Destination Sources","type":"main","index":0}]]}
    connections["Research Destination Sources"] = {"main":[[{"node":"Normalize Destination Sources","type":"main","index":0}]]}
    connections["Normalize Destination Sources"] = {"main":[[{"node":"Build Destination Extraction","type":"main","index":0}]]}
    connections["Build Destination Extraction"] = {"main":[[{"node":"Extract Destination Candidate","type":"main","index":0}]]}
    connections["Extract Destination Candidate"] = {"main":[[{"node":"Validate Destination Claim","type":"main","index":0}]]}
    connections["Validate Destination Claim"] = {"main":[[{"node":"Resolve Researched Destination","type":"main","index":0}]]}
    connections["Resolve Researched Destination"] = {"main":[[{"node":"Assemble Researched Destination","type":"main","index":0}]]}
    connections["Assemble Researched Destination"] = {"main":[[{"node":"Travel Tool Requested?","type":"main","index":0}]]}
    OUTPUT.write_text(json.dumps([workflow], indent=2) + "\n", encoding="utf-8")
    (ROOT / "workflows" / "jarvis-ii-pa-core-poc.json").write_text(json.dumps([workflow], indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
